### PR TITLE
Provide meaningful alt text for emoji

### PR DESCRIPTION
**Pull request by singingwolfboy**
Also switch to using the [twemoji library](https://twemoji.twitter.com/) for converting between Unicode code points and hex, instead of writing the functions ourselves.

### CODE REVIEW

**Comment by lfades** [comment]
@pacocoursey Can you help me with a review here 🙏

**Comment by lfades** [comment]
@singingwolfboy Thank you for the PR, this looks good to me, but I'll let @pacocoursey review it because I don't know if we need the `twemoji` library.

**Comment by singingwolfboy** [comment]
I figured that since the website is already using twemoji for _displaying_ emoji, it makes sense to use the library to convert to hex as well. After a bit more searching, I also found the [`emoji-unicode`](https://github.com/IonicaBizau/emoji-unicode) library, which does the same thing and might be more compact. I could switch to that, instead.

However, I should also point out that using the twemoji graphics requires attribution ([see the website](https://twemoji.twitter.com/)) and I don't see any attribution on the Zeit docs or in this codebase. Do you plan to add attribution soon?

**Comment by lfades** [comment]
@singingwolfboy The website doesn't have the `twemoji` package installed afaik

**Comment by singingwolfboy** [comment]
@lfades: the project is still using the Tweomji graphics, which requires attribution. However, that  is independent of the alt text issue addressed in this pull request, [so I've created a new GitHub issue for the Twemoji attribution issue](https://github.com/zeit/next-site/issues/562).

**Comment by singingwolfboy** [comment]
@lfades @pacocoursey: could I please get a review for this pull request? The alt text issue is still a problem.

**Comment by chibicode** [comment]
@singingwolfboy thank you so much and sorry for delay! Confirmed that it works by submitting the feedback w/ an emoji.

**Pull request merged**
