### PR TITLE
Handle nextjs.org/* links correctly

### PR DESCRIPTION
**Pull request by chibicode**
On [Getting Started](https://nextjs.org/docs/getting-started) page, if you click on the first link that says `learn course` it actually opens a new tab. This is because in the [original markdown file](https://github.com/zeit/next.js/blob/canary/docs/getting-started.md) the link points to `https://nextjs.org/learn/...`, which is an absolute URL, and `rehype` adds `target="_blank"` to such links.

Not sure if this approach is the best, but my quick fix removes `https://nextjs.org` from the URL before we process it.

### CODE REVIEW

**Comment by lfades** [comment]
@chibicode It's intended, all links in the content of the docs go to a new tab

**Comment by chibicode** [comment]
@lfades Ok, as a reader I thought it was strange that it opens a new tab even if the destination page is a different page on the same site. So I thought you could make an exception just for `nextjs.org/*` URLs in the doc. Also, if you select "Learn" from navbar it opens in the same tab, so I thought it should do the same for the "learn course" link. But I'd understand if this is such a minor detail that it's not worth making an exception for.

Artboard

**Comment by timneutkens** [comment]
@chibicode agreed those shouldn't open in a new tab 👍

**Comment by chibicode** [comment]
@lfades thanks for fixing!

**Pull request merged**
