### PR TITLE
Update Docs, fix wrong export

### PR DESCRIPTION
**Pull request by wzalazar**
This PR introduces

-  changes `export default Home` to `export default Index`

### CODE REVIEW

**Comment by timneutkens** [comment]
Is this wrong on github.com/zeit/next.js too?

**Comment by wzalazar** [comment]
@timneutkens on `github.com/zeit/next.js` all example are like this
```
function Home() {

}

export default Home
```

**Comment by timneutkens** [comment]
Right so we sync that readme with this one on new stable releases, so not sure what happened here 🤔

**Comment by atuttle** [comment]
Glad I thought to look before I submitted the same PR. I found the same bug, and it's still there https://nextjs.org/docs/

image

**Comment by timneutkens** [comment]
Fixed by @kheruc, pending deploy

**Pull request closed without merging**
