### PR TITLE
Add next/link support to markdown links for documentation

### PR DESCRIPTION
**Pull request by lfades**
The solution is quite hacky but works.

The alternative method could be to prefetch links with a mouse event and then handle the click event, that should work too.

The prefetching requests take something around 80-120ms to complete in my machine, so the prefetching added by `next/link` when the link enters the view is quite nice :relieved:

### CODE REVIEW

**Comment by chibicode** [comment]
This link doesn't seem to work 🤔 Other links are working.

Screen_Shot_2020-05-08_at_9_33_59_AM

https://next-site-git-docs-link.zeit.now.sh/docs/getting-started

Also, why did you use this method over using [`rehype-react`](https://github.com/rehypejs/rehype-react) to convert `a` tags to a custom component?

**Comment by chibicode** [comment]
Also, why did you use this method over using [`rehype-react`](https://github.com/rehypejs/rehype-react) to convert `a` tags to a custom component?

**Comment by lfades** [comment]
@chibicode `rehype-react` is a no go as it requires you have heavy packages in the browser, it would be better to return a minified ast and turn it into custom components by ourselves, which I also did and tested before doing this, unfortunately a very small ast wasn't always smaller than a html string and then there's that you have to add more JS to the client in order to handle custom components so I didn't see it as much of an improvement

**Comment by chibicode** [comment]
This link now works, but it seems to do hard refresh instead of client-side navigation:

Screen_Shot_2020-05-08_at_9_33_59_AM

**Pull request merged**
