### PR TITLE
Use 'next/head' for Head in document example

### PR DESCRIPTION
**Pull request by aguilarm**
Noticed this when I was creating a custom document. Before this change, the custom document example causes the error from https://github.com/zeit/next.js/issues/3518

### CODE REVIEW

**Comment by aguilarm** [comment]
This actually might just be the typescript compiler in which case the update might be unnecessary. These appear to be the same Head? I could be totally mistaken here. Either way popping this on the radar for ya'll.

**Comment by Timer** [comment]
This is the correct `<Head>` import for this example.
If you share more details, we may be able to help.

Thanks for your contribution!

**Comment by aguilarm** [comment]
@Timer yeah, jumped the gun here. Compiler no longer complaining. I got to the stale issue I linked via google and assumed the resolution hadn't trickled into docs but the resolution on that issue is actually incorrect.
Perhaps worth commenting on https://github.com/zeit/next.js/issues/3518 but I'm not sure if anyone else will encounter it.
Thanks!

**Comment by aguilarm** [comment]
Well, it's correct most of the time. Have to import next/head in non document and next/document in document. I'm getting more coffee, sorry about that. Thanks for closing!

**Comment by Timer** [comment]
@aguilarm we know it's confusing! We're going to figure out a better story for `next/head` in the future.

**Comment by Timer** [comment]
Added a comment, too: https://github.com/zeit/next.js/issues/3518#issuecomment-470183114

**Pull request closed without merging**
