### PR TITLE
Update dependencie:@mdx-js/tag --> @mdx-js/react

### PR DESCRIPTION
**Pull request by jschyz**
Change dependency

@mdx-js/tag0.20.3 --> @mdx-js/react@1.5.1

### CODE REVIEW

**Comment by lfades** [comment]
@jschyz Did you test this? I already know something is going to break

**Comment by jschyz** [comment]
> @jschyz Did you test this? I already know something is going to break

Yes, I tested it.

**Comment by lfades** [comment]
@jschyz It's broken here: https://next-site-2dwgo4s82.now.sh/docs

image

I already saw that issue when I did it myself before and didn't find a solution.

**Comment by lfades** [comment]
I'm closing this issue because updating MDX packages breaks the app, you are welcome to open it again if everything starts working as expected, thank you.

**Pull request closed without merging**
