### PR TITLE
Update docs.mdx

### PR DESCRIPTION
**Pull request by mayank23**
- fix runtime configuration example to use `customKey`
- standardize warning callouts to use a block quote and bold "**Warning:**" text. Previously there were different ways a warning was mentioned on the docs page:
  - A warning emoji. The warning emoji didn't render in the actual site. 
    Screen Shot 2019-03-21 at 9 22 21 AM
  - Italicized "Warning" text. Imo, does not stand out on the page.
    Screen Shot 2019-03-21 at 9 24 43 AM

### CODE REVIEW

**Comment by timneutkens** [comment]
Can you make these changes on the github.com/zeit/next.js readme? We sync it on stable releases 🙏

**Comment by mayank23** [comment]
Yup will do tonight 😃

**Comment by timneutkens** [comment]
❤️ amazing!

**Comment by mayank23** [comment]
@timneutkens done 😄 https://github.com/zeit/next.js/pull/6749

**Comment by timneutkens** [comment]
🚀 Amazing thank you @mayank23!

**Pull request closed without merging**
