### PR TITLE
Added "Setup" section in basics/deploying-a-nextjs-app/setup.mdx

### PR DESCRIPTION
**Pull request by kakakakakku**
Hi, thank you for awesome tutorial 👍

# What

Only `deploying-a-nextjs-app/setup.mdx` has NOT `## Setup` section in setup.mdx
See below.

```sh
$ grep "Setup" pages/learn/basics/*/setup.mdx
pages/learn/basics/api-routes/setup.mdx:## Setup
pages/learn/basics/clean-urls-with-dynamic-routing/setup.mdx:## Setup
pages/learn/basics/create-dynamic-pages/setup.mdx:## Setup
pages/learn/basics/fetching-data-for-pages/setup.mdx:## Setup
pages/learn/basics/getting-started/setup.mdx:## Setup
pages/learn/basics/navigate-between-pages/setup.mdx:## Setup
pages/learn/basics/styling-components/setup.mdx:## Setup
pages/learn/basics/using-shared-components/setup.mdx:## Setup
```

I added it.

# Image

image

It's very very small fix 🐰 
Thanks.

### CODE REVIEW

**Comment by kakakakakku** [comment]
Oh, why my pull request only failing "now" CI ?
Do you know reason why ?

**Comment by timneutkens** [comment]
@kakakakakku because we need to authorize deployments from external contributors.

**Comment by zeit-team** [comment]
#### 📝Changed routes:


| [**…ing-a-nextjs-app/setup**](https://next-site-git-fork-kakakakakku-fix-learn-basics-de-63b7ed.zeit.now.sh/learn/basics/deploying-a-nextjs-app/setup) |
|:-:|
|<a href="https://next-site-git-fork-kakakakakku-fix-learn-basics-de-63b7ed.zeit.now.sh/learn/basics/deploying-a-nextjs-app/setup">Screenshot of /learn/basics/deploying-a-nextjs-app/setup</a><br /><sup><a href="https://images.weserv.nl?url=https://microlink.nyc3.digitaloceanspaces.com/tiQg3okU45Ge1yGe_dZdyB2lqTQ_">(view full size)</a> |







Commit 5bdb8d47801873d7bdc23a204e46662deb92c6f2 (https://next-site-git-fork-kakakakakku-fix-learn-basics-de-63b7ed.zeit.now.sh).

**Comment by timneutkens** [comment]
Thank you!

**Pull request merged**
