### PR TITLE
Add feedback input to /learn

### PR DESCRIPTION
**Pull request by lfades**

### CODE REVIEW

**Comment by lfades** [comment]
@ijjk How does it look when you look at the entire page? - when I tested it, it felt kinda off if the content is larger than the sidebar, also it's centered with the content in our docs.

**Comment by ijjk** [comment]
I see, LGTM then 👍

**Comment by zeit-team** [comment]
#### 📝Changed routes:


| [**…ing-started/first-page**](https://next-site-git-learn-feedback.zeit.now.sh/learn/basics/getting-started/first-page) | [**…tween-pages/using-link**](https://next-site-git-learn-feedback.zeit.now.sh/learn/basics/navigate-between-pages/using-link) |
|:-:|:-:|
|<a href="https://next-site-git-learn-feedback.zeit.now.sh/learn/basics/getting-started/first-page">Screenshot of /learn/basics/getting-started/first-page</a><br /><sup><a href="https://images.weserv.nl?url=https://microlink.nyc3.digitaloceanspaces.com/WNMlZ85yjxtrFR7wvTnjzO8PW_s_">(view full size)</a> |<a href="https://next-site-git-learn-feedback.zeit.now.sh/learn/basics/navigate-between-pages/using-link">Screenshot of /learn/basics/navigate-between-pages/using-link</a><br /><sup><a href="https://images.weserv.nl?url=https://microlink.nyc3.digitaloceanspaces.com/qBZdIq_qCOdTDvgGADtuxhwnxMc_">(view full size)</a> |







Commit 27f5796adfac56152d6ccc4a7abec8e4ae309250 (https://next-site-git-learn-feedback.zeit.now.sh).

**Comment by timneutkens** [comment]
Merged in https://github.com/zeit/next-site/pull/542

**Pull request closed without merging**
