### PR TITLE
Add feedback widget to header

### PR DESCRIPTION
**Pull request by chibicode**
## TODO

- [ ] Incorporate a11y and sizing improvements

---

Adds a feedback widget to the site header.

- Basically copied this: https://github.com/zeit/docs/blob/master/components/feedback-input/header-feedback.js
- And modified some code to match this: https://github.com/zeit/next-site/blob/master/components/feedback.js

Note that it's completely hidden on:

- Mobile (similar to https://zeit.co/docs).
- Amp (so it'll be hidden on [the blog](https://next-site-git-fork-chibicode-header-feedback.zeit.now.sh/blog), which is amp-only)

## GIF

Kapture 2020-02-02 at 12 07 17

### CODE REVIEW

**Comment by chibicode** [comment]
@pacocoursey could you take a look at the design on this?

**Comment by zeit-team** [comment]
#### 📝Changed routes:


| [**/docs/\[...slug\]**](https://next-site-git-fork-chibicode-header-feedback.zeit.now.sh/docs/[...slug]) |
|:-:|
|<a href="https://next-site-git-fork-chibicode-header-feedback.zeit.now.sh/docs/[...slug]">Screenshot of /docs/[...slug]</a><br /><sup><a href="https://images.weserv.nl?url=https://microlink.nyc3.digitaloceanspaces.com/MJTyRVBnfJsW_yO_G55A455sI9o_">(view full size)</a> |







Commit cc80d9f0d62993602333c457e34f7e3b4e46deec (https://next-site-git-fork-chibicode-header-feedback.zeit.now.sh).

**Comment by pacocoursey** [comment]
In tablet viewports (~770px) and before our mobile viewport, the popup is cut off:

image

**Comment by chibicode** [comment]
@lfades @pacocoursey I made it such that the feedback widget would only show for viewports >= `951px`. Currently, under `951px` on docs pages, the side bar turns into a floating menu, and with the way things are set up right now, it's pretty complicated to get `z-index` to work correctly.

Kapture 2020-02-03 at 19 06 31

**Pull request merged**
